sqlite_default: &sqlite_default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

pg_default: &pg_default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


<% if BlackCandy.config.db_adapter == "postgresql" %>
development:
  primary: &primary_development
    <<: *pg_default
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    database: blackcandy_development
    host: localhost
  cache:
    <<: *primary_development
    database: blackcandy_development_cache
    migrations_paths: db/cache_migrate

test:
  primary: &primary_test
    <<: *pg_default
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    database: blackcandy_test
    host: localhost
  cache:
    <<: *primary_test
    database: blackcandy_test_cache
    migrations_paths: db/cache_migrate

production:
  primary: &primary_production
    <<: *pg_default
    url: <%= BlackCandy.config.db_url %>
  cache:
    <<: *primary_production
    url: <%= BlackCandy.config.cache_db_url %>
    migrations_paths: db/cache_migrate
<% else %>
development:
  primary:
    <<: *sqlite_default
    database: storage/development.sqlite3
  cache:
    <<: *sqlite_default
    database: storage/development_cache.sqlite3
    migrations_paths: db/cache_migrate

test:
  primary:
    <<: *sqlite_default
    database: storage/test.sqlite3
  cache:
    <<: *sqlite_default
    database: storage/test_cache.sqlite3
    migrations_paths: db/cache_migrate

production:
  primary:
    <<: *sqlite_default
    database: storage/production.sqlite3
  cache:
    <<: *sqlite_default
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
<% end %>
